version: '2.5'
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${DOCKER_ROOT}/sonarr:/config
      - ${DATA_ROOT}/tvshow:/tv
      - ${DATA_ROOT}/downloads:/downloads
    ports:
      - 8989:8989
    restart: no

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
    - ${DOCKER_ROOT}/radarr:/config
    - ${DATA_ROOT}/movies:/movies
    - ${DATA_ROOT}/downloads:/downloads
    ports:
    - 7878:7878
    restart: no

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - WEBUI_PORT=8080
    volumes:
    - ${DOCKER_ROOT}/qbittorrent:/config
    - ${DATA_ROOT}/downloads:/downloads
    ports:
    - 8080:8080
    - 6881:6881
    - 6881:6881/udp
    restart: no

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
    - ${DOCKER_ROOT}/bazarr:/config
    - ${DATA_ROOT}/subtitles:/subtitles
    - ${DATA_ROOT}/tvseries:/tvseries
    - ${DATA_ROOT}/movies:/movies
    ports:
    - 6767:6767
    restart: no

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    volumes:
    - ${DOCKER_ROOT}/prowlarr:/config
    ports:
    - 9696:9696
    restart: no
